# PayPal API Access Setup
#
# Instructions:
#
# 1. Go to https://developer.paypal.com/.
# 2. Create an account if you don't have one.
# 3. Click the "Test Accounts" on the left sidebar.
# 4. Create a Business Test Account if you don't have one.
# 5. Select the Business Test Account and click the "Enter Sandbox Test Site" button.
# 6. Once you log in, click "Profile."
# 7. Click on "API Access."
# 8. Click the "Request API Credentials" link.
# 9. Leave the default selection on "Request API signature" and click the "Agree and Submit" button.
# 10. Fill in api_username and api_password and api_signature with the given information.

# Development settings
development:
  api_username: "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
  api_password: "XXXXXXXXXXXXXXXX"
  api_signature: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  wiredump: true # Turn on logging of communications with PayPal during development

# Follow steps 6 to 10 but with your real PayPal account.
# NOTE: Your PayPal account must have Website Payments Pro already for this to work.

# Live settings
production:
  api_username: "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
  api_password: "XXXXXXXXXXXXXXXX"
  api_signature: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  # Don't turn this on in production mode unless you absolutely have to. It'll log people's credit card information
  wiredump: false 

# Common setting
# NOTE: This file is already provided for you. You don't need to download it again.
ca_file: "certs/api_cert_chain.crt"
