# Admin site login
admin_username: "admin"
admin_password: "password"

# Presentation stuf
company_name: "My Company"
company_url: "http://www.mycompany.com/"
company_logo_path: ""
store_name: "My Company Store"
copyright_html: "Copyright &copy; 2007 My Company. All rights reserved."
google_analytics_account: ""
include_mint: false
paypal_express_checkout_header_image: "https://www.mycompany.com/images/mylogo.png"

# Google checkout?
allow_google_checkout: true

# Email addresses
support_email: "support@mycompany.com"
sales_email: "sales@mycompany.com"

purchase_receipt_sender_email: "My Company <info@mycompany.com>"
purchase_receipt_bcc_email: "orders@mycompany.com"

lost_license_sent_notification_sender_email: "My Company <support@mycompany.com>"
lost_license_sent_notification_recipient_email: "info@mycompany.com"

crash_report_sender_email: "bugs@mycompany.com"
crash_report_recipient_email: "bugs@mycompany.com"

# Using SSL?
#
# Turning this on redirects most requests that come in through http to https
# In addition, if you're using Apache, you might need to add the following
# to its SSL configuration:
#
#		RequestHeader set X_FORWARDED_PROTO 'https'
#
redirect_to_ssl: true
